repos:
  - name: 
    - hello-world
    - assign_issues:
      - hakuna matata
    - assign_prs:
      - what a wonderful day

  - name:
    - repo2
  - assign_issues:
    - sofisl
  - assign_prs:
    - sofisl
