{
  "hello-world": {
    "assign_issues": [
      "hakuna matata",
      "what a wonderful day",
    ],
    "assign_prs": [
      "is a problem free",
      "philosophy"
    ]
  }, 
   "repo2": {
    "assign_issues": [
      "hakuna matata",
      "what a wonderful day",
    ],
    "assign_prs": [
      "is a problem free",
      "philosophy"
    ]
  }
}
     
