steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      git clone https://github.com/sofisl/testing-another-one.git && \
      cd testing-another-one/ && \
      git checkout -b dev && \
      git branch
    env:
      - 'GITHUB_TOKEN=$_GITHUB_TOKEN'
      - 'HOME=/workspace'
  - name: ${_CONTAINER}
    dir: /workspace/testing-another-one
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      ls
    dir: /workspace/testing-another-one
    env:
      - 'GITHUB_TOKEN=$_GITHUB_TOKEN'
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      git config --global user.email "sofialeon@google.com" && \
      git config --global user.name sofisl && \
      git add . && \
      git commit -m 'do the thing' && \
      git push --set-upstream origin dev
    env:
      - 'GITHUB_TOKEN=$_GITHUB_TOKEN'
    dir: testing-another-one
