on: push
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        env:
          SUPER_SECRET: ${{secrets.SUPER_SECRET}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          script: |
            console.info(process.env.SUPER_SECRET);
            console.info(process.env.GITHUB_TOKEN);
      - uses: actions/github-script@v3
        with:
          script: |
            console.info(process.env.SUPER_SECRET);
            console.info(process.env.GITHUB_TOKEN);
      - uses: bcoe/test-action-contract@b56de9fb5f97623c73058e77b8bffbe5d3d3ffc4
