on:
  push:
    branches:
      - master
name: release-please
jobs:
  changeFinder:
    runs-on: ubuntu-latest
    outputs:
      nodePaths: ${{ steps.interrogate.outputs.nodePaths }}
    steps:
      - uses: actions/checkout@v2
      - id: interrogate
        uses: actions/github-script@v3
        with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              const {execSync} = require('child_process');
              execSync('git pull --tags');
              const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
              const latestRelease = await github.repos.getLatestRelease({
                owner,
                repo
              });
              console.log(`latest release: ${JSON.stringify(latestRelease.data)}`);
              execSync(`git reset --hard ${latestRelease.data.tag_name}`);
              const status = execSync(`git diff --name-only origin/master`, { encoding: 'utf-8'});
              console.log(status);
              const changes = status.split('\n');
              let nodePaths = new Set();
              for (const change of changes) {
                if (change.startsWith('src/apis/')) {
                    nodePaths.add(change.split('/')[2]);
                };
              }
              nodePaths = Array.from(nodePaths);
              console.log(`::set-output name=nodePaths::${JSON.stringify(nodePaths)}`);
  release:
    runs-on: ubuntu-latest
    needs: changeFinder
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.changeFinder.outputs.nodePaths)}}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.7.0
        with:
           path: src/apis/${{ matrix.package }}
           token: ${{ secrets.CREATE_A_FORK }}
           release-type: node
           package-name: ${{ matrix.package }}
           monorepo-tags: true
